### ISSUE TITLE
Issue with Padrino

### ISSUE THREAD

**Issue by jnylen** [mwpastore/sinja#14]
Hi @mwpastore,
I have an issue trying to load sinja with Padrino.
The error is:
```
  ERROR -  NoMethodError - undefined method `+' for #<Mustermann::Regular:"\\/channels(?![^\\/])">:
 /home/vagrant/.rvm/gems/ruby-2.4.1/gems/sinatra-contrib-2.0.0/lib/sinatra/namespace.rb:332:in `prefixed_path'
/home/vagrant/.rvm/gems/ruby-2.4.1/gems/sinatra-contrib-2.0.0/lib/sinatra/namespace.rb:332:in `prefixed_path': undefined method `+' for #<Mustermann::Regular:"\\/channels(?![^\\/])"> (NoMethodError)
```

Basically the sub app loded is 
```ruby
require 'sinja'
require 'sinja/sequel/core'

module Server
  class ApiV3 < Padrino::Application
    #register Padrino::Mailer
    #register Padrino::Helpers
    register Sinja
    #enable :sessions

    #prerequisites << Padrino.root('api_v3', 'controller', '*.rb')

    resource :channel do

      index do
        Channel.all
      end

      # ..
    end

  end
end

```

**Comment by jnylen** [comment]
Got that error gone by forking padrino-core and replacing mustermann19 with mustermann.

But any of the resource :channel responds `Sinja::NotAcceptableError`

**Comment by mwpastore** [comment]
Hi @jnylen:

> Got that error gone by forking padrino-core and replacing mustermann19 with mustermann.

It looks like maybe Mustermann was forked to add support for Ruby 1.9, and this is the version Padrino is using, instead of the version of Mustermann that is used by Sinatra 2.0. Your fix may have gotten it to work for now, but there are likely other issues within Padrino if you use a different Mustermann. Does Padrino pass its test suite with your change? 

I cannot recommend using Sinja with Padrino at this time. Although Padrino is based on Sinatra and it *should* be fine, I have not tested it at all. I'm not familiar enough with what Padrino does to integrate with Sinatra, and how that might interfere with what Sinja does to integrate with Sinatra. Stick with vanilla Sinatra if you can. 

> But any of the resource :channel responds Sinja::NotAcceptableError

Are you following the [{json:api} specification](http://jsonapi.org/format/)? It sounds like you need to send an [Accept](http://jsonapi.org/format/#content-negotiation-clients) header with your requests. 😄

**Comment by jnylen** [comment]
@mwpastore,
Padrino tests passes for everything above 2.2.0.

Send a specific Accept with vnd.api thing didn't help. Could you try a sample padrino app on your side if it fails there too?

**Comment by mwpastore** [comment]
I can't commit to supporting Sinja in Padrino at this time. 

You sent `Accept: application/vnd.api+json`? What client library are you using? Can you try to get it working from the command-line with `curl`?

**Comment by jnylen** [comment]
I tried with curl, and I get 404:
`curl -H "Accept: application/vnd.api+json" http://localhost:2300/v3/channel` (and with /v3/channels)

**Comment by mwpastore** [comment]
Okay? Where is your application mounted? Is this Padrino still or Sinatra::Base? How were you structuring your requests to get the 406 errors in the first place?

**Comment by jnylen** [comment]
The app is mounted like:

`Padrino.mount('Server::ApiV3', :app_file => Padrino.root('api_v3/app.rb')).to('/v3')`

Ah, I got it working by using Sinatra::Base again.

Is it possible to show the API even though the user doesn't send Accept: application/vnd.api+json (or what its named) when they send Accept: */*? It won't show up in chrome. But will show up in curl.

**Comment by jnylen** [comment]
Got it working.

Fast as hell so far. Good job.

**Comment by mwpastore** [comment]
Great! Glad to hear it!
